version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    port:
      - 80:80
    networks:
      - gis_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_static:/data/static/
      - gis_media:/data/media/

  django:
    image: gis_django:3
    networks:
      - gis_network
    volumes:
    - gis_static:/home/gis_django_1/staticfiles/
    - gis_media:/home/gis_django_1/staticfiles/


networks:
  gis_network:


volumes:
  gis_static:
  gis_media: